@baseUrl = http://localhost:3000
@accessToken = {{signin.response.body.accessToken}}
@refreshAccessToken = {{refresh.response.body.accessToken}}
@refreshToken = {{signin.response.body.refreshToken}}

# @name signup
POST {{baseUrl}}/auth/signup
Content-Type: application/json
Authorization: Bearer {{{refreshAccessToken}}

{
    "firstName": "gustavo",
    "lastName": "dias",
    "username": "gustavo_dias",
    "email": "gustavodiasa2121@gmail.com",
    "password": "password123"
}

###

# @name signin
POST {{baseUrl}}/auth/signin
Content-Type: application/json

{
    "email": "gustavodiasa2121@gmail.com",
    "password": "password123"
}

###

# @name refresh
POST {{baseUrl}}/auth/refresh
Content-Type: application/json

{
    "refreshToken": "{{refreshToken}}"
}