@baseUrl = http://localhost:3000

# @name create_collection
POST {{baseUrl}}/collections
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMUpBMzZXODFaUkNFWks3NEM3Tkg4VFgxVyIsInBheWxvYWQiOnsiZW1haWwiOiJndXN0YXZvZGlhc2EyMTIxQGdtYWlsLmNvbSIsInVzZXJuYW1lIjoiZ3VzdGF2b19kaWFzIn0sImlhdCI6MTczMDA1MDc4NywiZXhwIjoxNzMwMDUxNjg3fQ.-e3UVG0AnCm3wp5YDIWlC0KvdZuznaVBLA6MxULb9OQ

{
    "name": "collection name",
    "description": "collection description",
    "theme": "collection theme"
}